### ISSUE TITLE
Проверка дз 1

### ISSUE THREAD

**Issue by LilyKras** [MeTpali/todoList#1]
**Чистота кода и общая структура проекта 2.5/4**
Есть up-to-date README со ссылкой на загрузку .apk, перечнем реализованных фич, пара скриншотов 0.5/1, тк нет скриншотов

Форматирование кода присутствует 1/1

Код разбит на фичи и слои (не важно, feature-first / layer-first) 1/2
Возможно имело бы смысл разбить TaskFormWidget на несколько частей и некоторые другие. 
Сложно ориентироваться в lib - не интуитивно 

**Вёрстка + навигация 11/16**
Полностью свёрстаны 2 экрана по макетам: основной и добавления/редактирования задачи 
5/10

_Основной:_

Ошибки:
- AppBar по макету другого цвета
- Очень странное поведение app bar на основном экране - двигается не ровно по диагонали (куда-то поплыл))) + выдает ошибку в консоли
- Надо бы заменить index на id и исходить из того, чтобы нельзя было по индексу в общем словаре определить содержание таски (данная концепция не подходит для работы с бд)
https://github.com/MeTpali/todoList/blob/10ea55e9248d211f1d03004af3d17d49e4c3c918/lib/ui/widgets/task_row/task_row_widget.dart#L15
https://github.com/MeTpali/todoList/blob/10ea55e9248d211f1d03004af3d17d49e4c3c918/lib/ui/widgets/main_screen/main_screen_widget_model.dart#L182-L192
- У Новое padding побольше в дизайне

Предложения:
- Имеет смысл сделать возможность отмечать выполненность дел с помощью checkbox

_Добавления/редактирования задачи (тут скорее предложения, а не ошибки):_
- AppBar по макету другого цвета
- Было бы прикольно сделать кнопку сохранить неактивной, если ничего не ввели, или выдавать ошибку (а то непонятно, почему ничего не происходит при нажатии на кнопку сохранить (приложение не работает? кнопка не работает?)
- Перфекционисту внутри меня не нравится, что важное из-за padding восклицательных знаков стоит не в ряд со всем остальным 

Свайп по айтему Выполнено/Удалить с логикой 3/3
Фон при свайпе выполнено другой по макету

Показ выполненных дел с логикой 3/3
Но иконка должна быть противоположной 

**Разное 6/6**
Реализовано нормальное логирование (не print'ы) 2/2

Есть человеческая иконка у приложения (iOS или Android) 4/4
Такая иконка для iphone не подойдет, если что (не пройдет проверку)

**Comment by MeTpali** [comment]
Спасибо за проверку. Насчёт аппбара, я не совсем понимаю как сделать без этих кринж действий), там ведь отступ слева на макете разный у аппбара. Если не затруднит, можете поделиться логами ошибки с аппбаром? (у меня их не было)

**Comment by LilyKras** [comment]
Сорри, не знаю как их норм отправить, могу лишь так 

flutter: The following assertion was thrown during performLayout():
flutter: SliverGeometry is not valid: The "layoutExtent" exceeds the "paintExtent".
flutter: The paintExtent is 92.55914831949923, but the layoutExtent is 92.55914831949924.
flutter: Maybe you have fallen prey to floating point rounding errors, and should explicitly apply the min()
flutter: or max() functions, or the clamp() method, to the layoutExtent?
flutter: The RenderSliver that returned the offending geometry was: _RenderSliverPinnedPersistentHeaderForWidgets#aa1ec relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT:
flutter:   creator: _SliverPinnedPersistentHeader ← SliverPersistentHeader ← Viewport ←
flutter:     IgnorePointer-[GlobalKey#fcc7e] ← Semantics ← Listener ← _GestureSemantics ←
flutter:     RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#4c368] ← Listener ← _ScrollableScope
flutter:     ← _ScrollSemantics-[GlobalKey#3358f] ← NotificationListener<ScrollMetricsNotification> ← ⋯
flutter:   parentData: paintOffset=Offset(0.0, 0.0) (can use size)
flutter:   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.reverse,
flutter:     scrollOffset: 27.4, remainingPaintExtent: 852.0, crossAxisExtent: 393.0, crossAxisDirection:
flutter:     AxisDirection.right, viewportMainAxisExtent: 852.0, remainingCacheExtent: 1129.4, cacheOrigin:
flutter:     -27.4)
flutter:   geometry: SliverGeometry(scrollExtent: 120.0, paintExtent: 92.6, layoutExtent: 92.6, maxPaintExtent:
flutter:     120.0, hasVisualOverflow: true, cacheExtent: 120.0)
flutter:   maxExtent: 120.0
flutter:   child position: 0.0
flutter:
flutter: The relevant error-causing widget was:
flutter:   SliverPersistentHeader
flutter:   SliverPersistentHeader:file:///Users/lilykrasnogorova/Flutter/projects/%D1%88%D0%BC%D1%80/todoList/lib/ui/widgets/main_screen/main_screen_widget.dart:34:13
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      SliverGeometry.debugAssertIsValid.<anonymous closure>.verify (package:flutter/src/rendering/sliver.dart:733:9)
lutter: #1      SliverGeometry.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/sliver.dart:746:9)
flutter: #2      SliverGeometry.debugAssertIsValid (package:flutter/src/rendering/sliver.dart:764:6)
flutter: #3      RenderSliver.debugAssertDoesMeetConstraints (package:flutter/src/rendering/sliver.dart:1211:22)
flutter: #4      RenderObject.layout.<anonymous closure> (package:flutter/src/rendering/object.dart:2398:9)
flutter: #5      RenderObject.layout (package:flutter/src/rendering/object.dart:2400:8)
flutter: #6      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:534:13)
flutter: #7      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1511:12)
flutter: #8      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1420:20)
flutter: #9      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2234:7)
flutter: #10     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1016:18)
flutter: #11     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:492:19)
flutter: #12     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:905:13)
flutter: #13     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
flutter: #14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
flutter: #15     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
flutter: #16     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072:5)
flutter: #17     _invoke (dart:ui/hooks.dart:142:13)
flutter: #18     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
flutter: #19     _drawFrame (dart:ui/hooks.dart:112:31)
flutter:
flutter: The following RenderObject was being processed when the exception was fired: _RenderSliverPinnedPersistentHeaderForWidgets#aa1ec relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT:
flutter:   creator: _SliverPinnedPersistentHeader ← SliverPersistentHeader ← Viewport ←
flutter:     IgnorePointer-[GlobalKey#fcc7e] ← Semantics ← Listener ← _GestureSemantics ←
flutter:     RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#4c368] ← Listener ← _ScrollableScope
flutter:     ← _ScrollSemantics-[GlobalKey#3358f] ← NotificationListener<ScrollMetricsNotification> ← ⋯
flutter:   parentData: paintOffset=Offset(0.0, 0.0) (can use size)
flutter:   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.reverse,
flutter:     scrollOffset: 27.4, remainingPaintExtent: 852.0, crossAxisExtent: 393.0, crossAxisDirection:
flutter:     AxisDirection.right, viewportMainAxisExtent: 852.0, remainingCacheExtent: 1129.4, cacheOrigin:
flutter:     -27.4)
flutter:   geometry: SliverGeometry(scrollExtent: 120.0, paintExtent: 92.6, layoutExtent: 92.6, maxPaintExtent:
flutter:     120.0, hasVisualOverflow: true, cacheExtent: 120.0)
flutter:   maxExtent: 120.0
flutter:   child position: 0.0
flutter: This RenderObject had the following descendants (showing up to depth 5):
flutter:     child: RenderStack#5aabc relayoutBoundary=up2 NEEDS-PAINT
flutter:       child 1: RenderPhysicalModel#c5a4f relayoutBoundary=up3 NEEDS-PAINT
flutter:         child: _RenderInkFeatures#857da relayoutBoundary=up4 NEEDS-PAINT
flutter:           child: RenderFlex#48757 relayoutBoundary=up5 NEEDS-PAINT
flutter:             child 1: RenderPadding#899ed relayoutBoundary=up6 NEEDS-PAINT
flutter:             child 2: RenderOpacity#d94b3 relayoutBoundary=up6 NEEDS-PAINT
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: SliverGeometry is not valid: The "layoutExtent" exceeds the

**Comment by LilyKras** [comment]
Если честно я тоже не очень поняла, как сделать этот app bar))

**Comment by MeTpali** [comment]
Спасибо, этого хватит https://github.com/MeTpali/todoList/issues/1#issuecomment-1597216152
Скоро лекция по анимациям вот и узнаем)
